export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as AboutUs } from './AboutUs/AboutUs';
export { default as Services } from './Services/Services';
export { default as Team } from './Team/Team';
export { default as Price } from './Price/Price';
export { default as Feedback } from './Feedback/Feedback';
export { default as Location } from './Location/Location';
export { default as Footer } from './Footer/Footer';